# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lodingwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LodingWidget(object):
    def setupUi(self, LodingWidget):
        LodingWidget.setObjectName("LodingWidget")
        LodingWidget.resize(500, 300)
        LodingWidget.setMinimumSize(QtCore.QSize(500, 300))
        LodingWidget.setMaximumSize(QtCore.QSize(500, 300))
        font = QtGui.QFont()
        font.setPointSize(16)
        LodingWidget.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(LodingWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(LodingWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEditUser = QtWidgets.QLineEdit(LodingWidget)
        self.lineEditUser.setObjectName("lineEditUser")
        self.horizontalLayout.addWidget(self.lineEditUser)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(LodingWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEditPassword = QtWidgets.QLineEdit(LodingWidget)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.horizontalLayout_2.addWidget(self.lineEditPassword)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.radioButtonRe = QtWidgets.QRadioButton(LodingWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButtonRe.setFont(font)
        self.radioButtonRe.setObjectName("radioButtonRe")
        self.verticalLayout.addWidget(self.radioButtonRe)
        self.pushButtonLog = QtWidgets.QPushButton(LodingWidget)
        self.pushButtonLog.setObjectName("pushButtonLog")
        self.verticalLayout.addWidget(self.pushButtonLog)
        self.pushButtonQuit = QtWidgets.QPushButton(LodingWidget)
        self.pushButtonQuit.setObjectName("pushButtonQuit")
        self.verticalLayout.addWidget(self.pushButtonQuit)
        self.VersionLab = QtWidgets.QLabel(LodingWidget)
        self.VersionLab.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.VersionLab.setTextFormat(QtCore.Qt.AutoText)
        self.VersionLab.setAlignment(QtCore.Qt.AlignCenter)
        self.VersionLab.setObjectName("VersionLab")
        self.verticalLayout.addWidget(self.VersionLab)
        self.label.setBuddy(self.lineEditUser)
        self.label_2.setBuddy(self.lineEditPassword)

        self.retranslateUi(LodingWidget)
        self.pushButtonQuit.clicked.connect(LodingWidget.close)
        QtCore.QMetaObject.connectSlotsByName(LodingWidget)

    def retranslateUi(self, LodingWidget):
        _translate = QtCore.QCoreApplication.translate
        LodingWidget.setWindowTitle(_translate("LodingWidget", "LodingWidget"))
        self.label.setText(_translate("LodingWidget", "账号名："))
        self.label_2.setText(_translate("LodingWidget", "密  码："))
        self.radioButtonRe.setText(_translate("LodingWidget", "记住密码"))
        self.pushButtonLog.setText(_translate("LodingWidget", "登录"))
        self.pushButtonQuit.setText(_translate("LodingWidget", "退出"))
        self.VersionLab.setText(_translate("LodingWidget", "10.1"))
